In [2]:
import numpy as np
import math
import sys

In [3]:
numberRange = [1,2,3,4,5,6,7,8,9,10,11,12,13]
colorRange =['Red', 'Black', 'Blue', 'Yellow']

In [4]:
boardList = [
    (7, 'Red'),
    (8, 'Red'),
    (9, 'Red'),
]

In [5]:
hand = [
    (6, 'Red'),
    (8, 'Blue'),
]

In [6]:
def makeMatrix(boardList):
    matrix = np.zeros(shape=[len(colorRange), len(numberRange)], dtype=int)
    for tile in boardList:
        numIdx = numberRange.index(tile[0])
        colIdx = colorRange.index(tile[1])
        matrix[colIdx, numIdx] += 1
    return matrix

testMatrix = makeMatrix(boardList)
print(testMatrix)

[[0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [7]:
def checkPlanIsValid(plan):
    for group in plan:

        if len(group) < 3:
            return 'Group too short'

        numbersList = [tile[0] for tile in group]
        colorsList = [tile[1] for tile in group]
        numbersSet = set(numbersList)
        colorsSet = set(colorsList)

        isGroupOfNumbers = len(numbersSet) > 1
        isGroupOfColors = len(colorsSet) > 1

        if isGroupOfNumbers and isGroupOfColors:
            return 'Number group and color group'
        
        if isGroupOfNumbers:
            
            # Check numbers are consecutive
            sortedNumbers = np.sort(numbersList)
            sortedNumbersDiff = np.diff(sortedNumbers)
            if not np.all(sortedNumbersDiff == 1):
                return 'Number group not consecutive'

        if isGroupOfColors:
            if len(colorsSet) < len(colorsList):
                # There must be a color double up
                return 'Color group with double up'

    return True

In [8]:
# Testing checkPlanIsValid
assert checkPlanIsValid([ [(6, 'Red'), (7, 'Red'), (8, 'Red')] ]) == True, 'Does not work for normal group of numbers'
assert checkPlanIsValid([ [(10, 'Blue'), (10, 'Red'), (10, 'Black')] ]) == True, 'Does not work for normal group of colors'
assert checkPlanIsValid([ [(6, 'Red'), (7, 'Red'), (9, 'Red')] ]) != True, 'Does not catch gap in group of numbers'
assert checkPlanIsValid([ [(6, 'Red'), (7, 'Red'), (8, 'Blue')] ]) != True, 'Does not catch group with multiple numbers and multiple colors'
assert checkPlanIsValid([ [(6, 'Red'), (6, 'Red'), (7, 'Red')] ]) != True, 'Does not catch number group with double ups'
assert checkPlanIsValid([ [(10, 'Red'), (10, 'Red'), (10, 'Black')] ]) != True, 'Does not catch color group with double ups'
assert checkPlanIsValid([ [(10, 'Red'), (10, 'Black')] ]) != True, 'Does not catch color group with two tiles'
assert checkPlanIsValid([ [(6, 'Red'), (7, 'Red')] ]) != True, 'Does not catch number group with two tiles'
assert checkPlanIsValid([ [(num, 'Red') for num in numberRange] ]) == True, 'Does not allow large number group'
assert checkPlanIsValid([
    [(6, 'Red'), (7, 'Red'), (8, 'Red')],
    [(10, 'Blue'), (10, 'Red'), (10, 'Black'), (10,'Yellow')],
]) == True, 'Does not work with multiple  groups'
assert checkPlanIsValid([
    [(6, 'Red'), (7, 'Red'), (8, 'Red')],
    [(10, 'Red'), (10, 'Red')],
]) != True, 'Does not catch bad group in multiple groups'

In [9]:
def groupMapToPlan(tiles, groupMap):
    numGroups = max(groupMap)+1
    plan = [[] for _ in range(numGroups)]
    for tileIdx in range(len(groupMap)):
        groupIdx = groupMap[tileIdx]
        tile = tiles[tileIdx]
        plan[groupIdx].append(tile)

    return plan
    
tiles =  [
    (1, 'Red'),
    (2, 'Red'),
    (3, 'Red'),
    (10, 'Red'),
    (10, 'Black'),
    (10, 'Blue'),
]

groupMap = [
    0,
    0,
    0,
    1,
    1,
    1,
]

plan = groupMapToPlan(tiles, groupMap)
print(plan)

[[(1, 'Red'), (2, 'Red'), (3, 'Red')], [(10, 'Red'), (10, 'Black'), (10, 'Blue')]]


In [10]:
def solvePlanFromTilesWithBacktracking(tiles):
    groupMap = np.zeros(shape=np.size(tiles))
    currentTileIdx = 0
    velocity = 0
    numTiles = len(tiles)
    maxGroup = math.floor(numTiles/3)
    complete = False
    iterations = 0
    maxIterations = 1000
    while (currentTileIdx < numTiles) and (not complete) and (iterations < maxIterations):
        res = checkPlanIsValid(groupMapToPlan(tiles, groupMap))
        if res != True:
            currentGroup = groupMap[currentTileIdx]
            # if currentGroup == 

    if iterations == maxIterations:
        print('Maxed out on iterations')
    

In [11]:
def solvePlanFromTilesWithBruteForce(tiles):
    numTiles = len(tiles)
    numGroups = math.floor(numTiles/3)
    numIterations = numGroups ** numTiles
    print('numTiles', numTiles)
    print('numGroups', numGroups)
    print('numIterations', numIterations)
    solns = []
    for i in range(numIterations):
        groupMap = np.zeros(shape=[numTiles], dtype=np.int8)

        for tileIdx in range(numTiles):
            divisor = numGroups ** tileIdx
            premod = math.floor(i / divisor)
            group = premod % numGroups
            groupMap[tileIdx] = group

        # print(groupMap)
        if checkPlanIsValid(groupMapToPlan(tiles, groupMap)) == True:
            solns.append(groupMap)

    return solns

In [12]:
tiles =  [
    (6, 'Red'),
    (7, 'Red'),
    (8, 'Red'),
    (9, 'Red'),
    (10, 'Red'),
    (10, 'Yellow'),
    (10, 'Black'),
    (10, 'Blue'),
    (13, 'Blue'),
]

# solvePlanFromTilesWithBruteForce(tiles)

In [13]:
kernals = np.array([
    [
        [1,1,1,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
    ],
    [
        [0,1,1,1,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
    ],
    [
        [0,0,1,1,1],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
    ],
    [
        [0,0,1,0,0],
        [0,0,0,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0],
    ],
    [
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,0,0,0],
        [0,0,1,0,0],
    ],
    [
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,0,0,0],
    ],
])

def checkKernalsInMatrix(matrix, kernalIdxs, colorIdx, numberIdx):
    kernal = np.sum([kernals[kernalIdx] for kernalIdx in kernalIdxs], 0)
    for kernalRowIdx in range(len(kernal)):
        for kernalColIdx in range(len(kernal[0])):
            kernalVal = kernal[kernalRowIdx, kernalColIdx]
            if kernalVal > 0:
                matrixRowIdx = (kernalRowIdx + colorIdx) % len(colorRange)
                matrixColIdx = (kernalColIdx - 2 + numberIdx + len(numberRange)) % len(numberRange)
                matrixVal = matrix[matrixRowIdx, matrixColIdx]
                if matrixVal < kernalVal:
                    return False
    
    return True

def kernalToGroup(kernalIdx, colorIdx, numberIdx):
    kernal = kernals[kernalIdx]
    group = []
    for kernalRowIdx in range(len(kernal)):
        for kernalColIdx in range(len(kernal[0])):
            kernalVal = kernal[kernalRowIdx, kernalColIdx]
            if kernalVal > 0:
                matrixRowIdx = (kernalRowIdx + colorIdx) % len(colorRange)
                matrixColIdx = (kernalColIdx - 2 + numberIdx + len(numberRange)) % len(numberRange)
                color = colorRange[matrixRowIdx]
                number = numberRange[matrixColIdx]
                group.append((number, color))
    return group

def replace_submatrix(A, rows, cols, B):
  for idx, row in enumerate(rows):
    A[row, cols] = B[idx, :]
  return A
  
def kernalToMatrix(kernalIdx, colorIdx, numberIdx):
    kernal = np.array(kernals[kernalIdx], dtype=int)
    mat = np.zeros(shape=[len(colorRange), len(numberRange)], dtype=int)
    rows = (np.arange(len(kernal)) + colorIdx) % len(colorRange)
    cols = (np.arange(len(kernal[0])) - 2 + numberIdx + len(numberRange)) % len(numberRange)
    mat = replace_submatrix(mat, rows, cols, kernal)
    return mat

def solveMatrixAnalytically(matrix, plan):
    keepGoing = True
    optionsMat = np.zeros(shape=np.shape(matrix), dtype=int)
    while keepGoing == True:
        keepGoing = False

        # Check kernals on each tile
        for colorIdx in range(len(colorRange)):
            for numberIdx in range(len(numberRange)):
                quantityOfTile = matrix[colorIdx,numberIdx] # Is either 0, 1 or 2
                if quantityOfTile == 0:
                    continue

                elif quantityOfTile == 1:
                    kernalsThatWork = set()
                    for kernalIdx in range(len(kernals)):
                        works = checkKernalsInMatrix(matrix, [kernalIdx], colorIdx, numberIdx)
                        if works:
                            kernalsThatWork.add(kernalIdx)

                    numOptions = len(kernalsThatWork)
                    optionsMat[colorIdx, numberIdx] = numOptions
                    if numOptions == 0:
                        print(f'\n Uh oh no options. {(colorRange[colorIdx], numberRange[numberIdx])}')                    

                    if numOptions == 1:
                        print(f'\n Found one. {(colorRange[colorIdx], numberRange[numberIdx])}. kernalsThatWork: {kernalsThatWork}')                    

                        # Unpack single kernel from set
                        (kernalIdx, ) = kernalsThatWork
                        # Add kernal to plan
                        group = kernalToGroup(kernalIdx, colorIdx, numberIdx)
                        plan.append(group)
                        # Remove kernal from matrix
                        matrix -= kernalToMatrix(kernalIdx, colorIdx, numberIdx)

                        print(matrix)
                        print(plan)

                elif quantityOfTile == 2:
                    kernalsPairsThatWork = set()
                    for kernalIdx1 in range(len(kernals)):
                        for kernalIdx2 in range(len(kernals)):
                            works = checkKernalsInMatrix(matrix, [kernalIdx1, kernalIdx2], colorIdx, numberIdx)
                            if works:
                                kernalsPairsThatWork.add( frozenset({kernalIdx1, kernalIdx2}) )
                    
                    numOptions = len(kernalsPairsThatWork)
                    optionsMat[colorIdx, numberIdx] = numOptions

                    if numOptions == 0:
                        print(f'\n Uh oh no options. {(colorRange[colorIdx], numberRange[numberIdx])}')                    

                    if numOptions == 1:
                        keepGoing = True
                        print(f'\n Found a pair. {(colorRange[colorIdx], numberRange[numberIdx])}. kernalsPairsThatWork: {kernalsPairsThatWork}')                    

                        # Unpack single kernel pair from set
                        (kernalPair, ) = kernalsPairsThatWork
                        for kernalIdx in kernalPair:
                            # Add kernal to plan
                            group = kernalToGroup(kernalIdx, colorIdx, numberIdx)
                            plan.append(group)
                            # Remove kernal from matrix
                            matrix -= kernalToMatrix(kernalIdx, colorIdx, numberIdx)

                            print(matrix)
                            print(plan)
                        
                else:
                    input('ERROR rweqdfvw. Wrong quantity of tile. Press enter to end: ')
                    sys.exit()
                
    optionsMat[matrix == 0] = -1
    print("\n optionsMat")
    print(optionsMat)
    return (matrix,  plan)

# matrix =  np.array([
#     # 1  2  3  4  5  6  7  8  9 10 11 12 13
#     [ 0, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2], # Red
#     [ 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2], # Black
#     [ 2, 1, 1, 1, 2, 0, 2, 1, 2, 0, 1, 1, 2], # Blue
#     [ 1, 0, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1], # Yellow
# ], dtype=int)
matrix =  np.array([
    # 1  2  3  4  5  6  7  8  9 10 11 12 13
    [ 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 2, 2, 1], # Red
    [ 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 2, 0, 1], # Black
    [ 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2], # Blue
    [ 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1], # Yellow
], dtype=int)
plan = []

print('\n BEFORE')
print('matrix:')
print(matrix)
# print('plan:')
# print(plan)

(matrix, plan) = solveMatrixAnalytically(matrix, plan)
# print('\n AFTER')
# print('matrix:')
# print(matrixAfter)
# print('plan:')
# print(planAfter)


 BEFORE
matrix:
[[0 2 1 1 2 1 2 2 1 1 2 1 2]
 [1 2 1 1 2 2 2 2 2 2 2 2 2]
 [2 1 1 1 2 0 2 1 2 0 1 1 2]
 [1 0 1 1 2 2 2 1 1 2 2 2 1]]

 Found a pair. ('Red', 2). kernalsPairsThatWork: {frozenset({2, 5})}
[[0 1 0 0 2 1 2 2 1 1 2 1 2]
 [1 2 1 1 2 2 2 2 2 2 2 2 2]
 [2 1 1 1 2 0 2 1 2 0 1 1 2]
 [1 0 1 1 2 2 2 1 1 2 2 2 1]]
[[(2, 'Red'), (3, 'Red'), (4, 'Red')]]
[[0 0 0 0 2 1 2 2 1 1 2 1 2]
 [1 1 1 1 2 2 2 2 2 2 2 2 2]
 [2 0 1 1 2 0 2 1 2 0 1 1 2]
 [1 0 1 1 2 2 2 1 1 2 2 2 1]]
[[(2, 'Red'), (3, 'Red'), (4, 'Red')], [(2, 'Red'), (2, 'Black'), (2, 'Blue')]]

 Found a pair. ('Blue', 1). kernalsPairsThatWork: {frozenset({0, 4})}
[[0 0 0 0 2 1 2 2 1 1 2 1 2]
 [1 1 1 1 2 2 2 2 2 2 2 2 2]
 [1 0 1 1 2 0 2 1 2 0 1 0 1]
 [1 0 1 1 2 2 2 1 1 2 2 2 1]]
[[(2, 'Red'), (3, 'Red'), (4, 'Red')], [(2, 'Red'), (2, 'Black'), (2, 'Blue')], [(12, 'Blue'), (13, 'Blue'), (1, 'Blue')]]
[[0 0 0 0 2 1 2 2 1 1 2 1 2]
 [0 1 1 1 2 2 2 2 2 2 2 2 2]
 [0 0 1 1 2 0 2 1 2 0 1 0 1]
 [0 0 1 1 2 2 2 1 1 2 2 2 1]]
[[(2, 'Red'), (

In [18]:
import moment
numberOfUniqueTripletGroups = int(sum(sum(matrix)) / 3)
numberOfTests = 2 ** numberOfUniqueTripletGroups
print(f'The number of unique triplet groups is {numberOfUniqueTripletGroups} which would take {numberOfTests} tests')


The number of unique triplet groups is 18 which would take 262144 tests
